spring:
  datasource:
    username: oirlife
    password: Oirlfe2023..
    url: jdbc:mysql://112.230.195.142:3306/oirlife_main?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
generate:
  template: mybatis-plus
  autoGenerate: gmt_created,gmt_modified
  deleteName:
  basePackage: com.oirlife.fulfillment
  enableSwagger: true
  tablePrefix: f_
  tables:
    - tableName: f_exam_fulfillment