spring:
  datasource:
    username: oirlife
    password: Oirlfe2023..
    url: jdbc:mysql://112.230.195.142:3306/test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
generate:
  template: mybatis-plus
  autoGenerate: gmt_created,gmt_modified,is_deleted
  deleteName: is_deleted
  basePackage: wang.hongxiang.customer
  enableSwagger: true
  tablePrefix:
  tables:
    - tableName: user_real
    - tableName: user_info