spring:
  datasource:
    username: www
    password: 123456
    url: jdbc:mysql://192.168.1.49:3306/catnip_main?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
generate:
  template: mybatis-plus
  author: catnip
  basePackage: com.dw.common
  enableSwagger: true
  tablePrefix: tb
  tables:
    - tableName: tb_common_web_log