spring:
  datasource:
    username: root
    password: Wang2008..
    url: jdbc:mysql://192.168.122.53:32306/catnip_main?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
generate:
  template: default
  author: whx
  tablePrefix: tb_
  basePackage: cn.catnip.common
  enableSwagger: false
  tables:
    - tableName: tb_common_web_log
      autoGenerate: id,gmt_created
      deleteName: is_deleted