spring:
  datasource:
    username: root
    password: Wang2008..
    url: jdbc:mysql://catnip.cn:32306/catnip_main?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
generate:
  template: default
  author: catnip
  basePackage: cn.catnip.user
  enableSwagger: true
  tablePrefix: tb
  tables:
    - tableName: tb_user
      autoGenerate: id,gmt_created,is_deleted
      deleteName: is_deleted